### ISSUE TITLE
How is .env being read?

### ISSUE THREAD

**Issue by MrSkinny** [Thinkful-Ed/node-jwt-auth#2]
@benjaminEwhite @oampo
Noticed in the lesson it says you'll need to create `.env` file for the `JWT_SECRET` etc. but I'm not seeing how this will be read.  Don't you need the `dot-env` package or similar?

**Comment by oampo** [comment]
Yep, it's read using `dotenv`:

https://github.com/Thinkful-Ed/node-jwt-auth/blob/master/package.json#L16
https://github.com/Thinkful-Ed/node-jwt-auth/blob/master/server.js#L1

**Comment by veborich** [comment]
Ah I was working from @cklanac's fork to review a frontend add for fulltime, which for some reason has lost the [dot-env require](https://github.com/cklanac/node-jwt-auth/blob/master/server.js#L1) ...

**Comment by MrSkinny** [comment]
Ah I was working from @cklanac's fork to review a frontend add for fulltime, which for some reason has lost the [dot-env require](https://github.com/cklanac/node-jwt-auth/blob/master/server.js#L1) ...
